name: Update Playlist Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-dotenv requests

      - name: Run update script
        run: python update_script.py

      - name: Commit and push if file changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add artl.m3u || echo "No playlist file to add"
          git commit -m "Auto update artl.m3u" || echo "No changes to commit"
          git push || echo "Nothing to push"
